"""Add default Client rol, for new users

Revision ID: 9971f6b3ea13
Revises: 86d99681e6ba
Create Date: 2020-12-20 20:10:15.404730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9971f6b3ea13'
down_revision = '86d99681e6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'rol', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
